ruby '2.0.0'

source 'https://rubygems.org'

gem 'pg'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'rack-contrib'
gem 'railties'
gem "activerecord", "~> 4.0.0"

gem 'redis'
gem 'connection_pool'
gem 'pusher'
gem 'eventmachine'
gem "em-http-request", "~> 1.1.1"
gem "thin"



gem 'dotenv', :groups => [:development, :test]
gem 'rspec', groups: [:test]

