source 'https://rubygems.org'

ruby '2.0.0'

gem 'airbrake'
gem 'bourbon'
gem 'coffee-rails'
gem 'delayed_job_active_record', '>= 4.0.0'
gem 'email_validator'
gem 'flutie'
gem 'high_voltage'
gem 'jquery-rails'
gem 'neat'
gem 'pg'
gem 'rack-timeout'
gem 'rails', '>= 4.0.0'
gem 'recipient_interceptor'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'puma'
gem 'devise'
gem 'dashing-rails', github: "dierbro/dashing-rails", branch: "remove-sse"
gem 'zeroclipboard-rails'


gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails', :github => 'anjlab/bootstrap-rails'
gem 'ledermann-rails-settings', :require => 'rails-settings'

gem 'yui-compressor'

gem 'pusher'
gem 'redis'
gem 'connection_pool'
gem 'deep_cloneable', '~> 1.6.0'

gem 'dotenv-rails', :groups => [:development, :test]
gem "letter_opener", :group => :development


gem 'rails-i18n', '~> 4.0.0' 
gem 'devise-i18n'
gem 'postmark-rails', '~> 0.5.2'
gem 'google-analytics-rails'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
  gem "rails-erd"
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails', '>= 2.14'
end

group :test do
  gem 'capybara-webkit', '>= 1.0.0'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'webmock'
  gem "shoulda-matchers"
end

group :staging, :production do
  gem 'newrelic_rpm', '>= 3.7'
  gem 'rails_12factor'
end
